### ISSUE TITLE
Practice mode test noclips you into block when dying (and more)

### ISSUE THREAD

**Issue by LNLenost** [famidash/famidash#80] opened 2024-04-27 16:51 UTC
Not only it lets you noclip into blocks and puts you into a loophole. Whenever you die and you respawn to a checkpoint the background color resets to blue and the music restarts from the beginning.

I'm pretty sure you know me and my device now (Nostalgia.NES Pro and Famidash nightly)

https://github.com/famidash/famidash/assets/110625168/33229cd8-cba9-4f32-be52-32e3d3be49e8

**Comment by kandowontu** [comment] 2024-04-27 17:15
Can you try this again with the latest nightly? I can't reproduce it.

**Comment by kandowontu** [comment] 2024-04-27 17:15
ok never mind, there are def some practice mode issues,

**Comment by kandowontu** [comment] 2024-04-27 17:18
Besides the color not saving, occassionally I do get a strange offsetted layout, but I still cannot reproduce what you had happen.

**Comment by LNLenost** [comment] 2024-04-27 17:32
Here's a full recording, just downloaded latest nightly


https://github.com/famidash/famidash/assets/110625168/f48b2da6-f7b8-4292-b49b-4585498e479f

**Comment by LNLenost** [comment] 2024-04-27 17:33
> Here's a full recording, just downloaded latest nightly
> 
> 
> https://github.com/famidash/famidash/assets/110625168/f48b2da6-f7b8-4292-b49b-4585498e479f
> 
> 


Issue comes at 0:08

**Comment by kandowontu** [comment] 2024-04-27 17:34
amazing xD
This *may* be the best we can get, we may just have to add a disclaimer that practice mode can be broken easily so use it properly and cross your fingers.

**Comment by LNLenost** [comment] 2024-04-27 17:35
> amazing xD
> This *may* be the best we can get, we may just have to add a disclaimer that practice mode can be broken easily so use it properly and cross your fingers.

Ok

**Comment by kandowontu** [comment] 2024-04-27 17:36
Leaving issue open in case someone wants to revisit this.

**Comment by kandowontu** [comment] 2024-04-29 01:14
More info: issue #105

**Comment by kandowontu** [comment] 2024-05-01 22:02
MAY be fixed in [986db24](https://github.com/famidash/famidash/commit/986db24bf3eaaf8cced5e219a9495002d13c55db) - need more testing, but I can no longer duplicate this (yes there are still music bugs)

**Comment by kandowontu** [comment] 2024-05-02 00:46
Practice mode now restores colors properly - the only thing left is music issues

**Comment by kandowontu** [comment] 2024-05-02 13:39
Unless someone can reproduce this issue again, closing this

**Closed by kandowontu** 2024-05-02 13:39 UTC
Labels: may be worked on

**Comment by LNLenost** [comment] 2024-05-02 14:01
Cant replicate this as of now
